Repository communitiesuk/ukraine-sponsor-resettlement, pull requests merged in 2022-08, with the labels that each got.

#222 Bundle updates
  Gemfile.lock
Labels: dependencies

#224 785 tasklist behaviour bug
  app/models/unaccompanied_minor.rb
  spec/models/unaccompanied_minor_spec.rb
Labels: bug

#227 Resident details section not being included in the count of complete sections
  app/controllers/unaccompanied_controller.rb
  app/models/unaccompanied_minor.rb
  app/views/sponsor-a-child/task_list.html.erb
  spec/models/unaccompanied_minor_spec.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: enhancement

#233 Correct the colour used when additional household members are marked as completed
  app/views/sponsor-a-child/task_list.html.erb
Labels: bug

#235 753 dates in form fixes
  app/controllers/unaccompanied_controller.rb
  app/models/concerns/uam_validations.rb
  app/models/unaccompanied_minor.rb
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
  spec/controllers/unaccompanied_controller_spec.rb
  spec/models/unaccompanied_minor_spec.rb
Labels: enhancement

#240 Save and return later
  Gemfile.lock
  app/controllers/token_based_resume_controller.rb
  app/controllers/unaccompanied_controller.rb
  app/views/sponsor-a-child/start.html.erb
  app/views/sponsor-a-child/steps/10.html.erb
  app/views/sponsor-a-child/steps/11.html.erb
  app/views/sponsor-a-child/steps/12.html.erb
  app/views/sponsor-a-child/steps/13.html.erb
  app/views/sponsor-a-child/steps/14.html.erb
  app/views/sponsor-a-child/steps/15.html.erb
  app/views/sponsor-a-child/steps/16.html.erb
  app/views/sponsor-a-child/steps/17.html.erb
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/19.html.erb
  app/views/sponsor-a-child/steps/20.html.erb
  app/views/sponsor-a-child/steps/21.html.erb
  app/views/sponsor-a-child/steps/22.html.erb
  app/views/sponsor-a-child/steps/23.html.erb
  app/views/sponsor-a-child/steps/24.html.erb
  app/views/sponsor-a-child/steps/25.html.erb
  app/views/sponsor-a-child/steps/26.html.erb
  app/views/sponsor-a-child/steps/27.html.erb
  app/views/sponsor-a-child/steps/28.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/30.html.erb
  app/views/sponsor-a-child/steps/31.html.erb
  app/views/sponsor-a-child/steps/32.html.erb
  app/views/sponsor-a-child/steps/33.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
  app/views/sponsor-a-child/steps/35.html.erb
  app/views/sponsor-a-child/steps/36.html.erb
  app/views/sponsor-a-child/steps/37.html.erb
  app/views/sponsor-a-child/steps/38.html.erb
  app/views/sponsor-a-child/steps/39.html.erb
  app/views/sponsor-a-child/task_list.html.erb
  app/views/token-based-resume/save_return_confirm.html.erb
  app/views/token-based-resume/save_return_resend_link.html.erb
  config/routes.rb
  spec/system/token_based_resume_controller_spec.rb
Labels: enhancement

#244 Show scrambled email address after Save and return (confirm screen)
  app/controllers/token_based_resume_controller.rb
  app/views/token-based-resume/save_return_confirm.html.erb
  spec/system/token_based_resume_controller_spec.rb
Labels: enhancement

#245 Nationality dropdown default invalid value
  app/controllers/unaccompanied_controller.rb
  app/helpers/application_helper.rb
  app/views/sponsor-a-child/steps/21.html.erb
  config/locales/en.yml
  spec/system/unaccompanied_minor_spec.rb
Labels: bug

#247 Put save-and-return behind feature flag
  .github/workflows/deploy-pipeline.yml
  app/controllers/unaccompanied_controller.rb
  app/views/sponsor-a-child/start.html.erb
  app/views/sponsor-a-child/steps/10.html.erb
  app/views/sponsor-a-child/steps/11.html.erb
  app/views/sponsor-a-child/steps/12.html.erb
  app/views/sponsor-a-child/steps/13.html.erb
  app/views/sponsor-a-child/steps/14.html.erb
  app/views/sponsor-a-child/steps/15.html.erb
  app/views/sponsor-a-child/steps/16.html.erb
  app/views/sponsor-a-child/steps/17.html.erb
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/19.html.erb
  app/views/sponsor-a-child/steps/20.html.erb
  app/views/sponsor-a-child/steps/21.html.erb
  app/views/sponsor-a-child/steps/22.html.erb
  app/views/sponsor-a-child/steps/23.html.erb
  app/views/sponsor-a-child/steps/24.html.erb
  app/views/sponsor-a-child/steps/25.html.erb
  app/views/sponsor-a-child/steps/26.html.erb
  app/views/sponsor-a-child/steps/27.html.erb
  app/views/sponsor-a-child/steps/28.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/30.html.erb
  app/views/sponsor-a-child/steps/31.html.erb
  app/views/sponsor-a-child/steps/32.html.erb
  app/views/sponsor-a-child/steps/33.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
  app/views/sponsor-a-child/steps/35.html.erb
  app/views/sponsor-a-child/steps/36.html.erb
  app/views/sponsor-a-child/steps/37.html.erb
  app/views/sponsor-a-child/steps/38.html.erb
  app/views/sponsor-a-child/steps/39.html.erb
  app/views/sponsor-a-child/task_list.html.erb
Labels: enhancement

#252 876 other adults nationality should reload
  app/controllers/unaccompanied_controller.rb
  spec/system/unaccompanied_minor_other_adults_spec.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: bug

#253 878 - Fix name validation
  app/controllers/unaccompanied_controller.rb
  app/models/concerns/additional_info_validations.rb
  app/models/concerns/common_validations.rb
  app/models/concerns/contact_details_validations.rb
  app/models/concerns/uam_validations.rb
  app/views/sponsor-a-child/steps/12.html.erb
  spec/models/concerns/common_validations_spec.rb
Labels: bug

#255 Save and return multiple applications
  app/controllers/token_based_resume_controller.rb
  app/views/token-based-resume/select_multiple_applications.erb
  config/routes.rb
  spec/controllers/token_based_resume_controller_spec.rb
  spec/system/token_based_resume_controller_spec.rb
Labels: enhancement

#251 Save and return continued
  app/controllers/token_based_resume_controller.rb
  app/controllers/unaccompanied_controller.rb
  app/views/sponsor-a-child/start.html.erb
  app/views/sponsor-a-child/steps/10.html.erb
  app/views/sponsor-a-child/steps/11.html.erb
  app/views/sponsor-a-child/steps/12.html.erb
  app/views/sponsor-a-child/steps/13.html.erb
  app/views/sponsor-a-child/steps/14.html.erb
  app/views/sponsor-a-child/steps/15.html.erb
  app/views/sponsor-a-child/steps/16.html.erb
  app/views/sponsor-a-child/steps/17.html.erb
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/19.html.erb
  app/views/sponsor-a-child/steps/20.html.erb
  app/views/sponsor-a-child/steps/21.html.erb
  app/views/sponsor-a-child/steps/22.html.erb
  app/views/sponsor-a-child/steps/23.html.erb
  app/views/sponsor-a-child/steps/24.html.erb
  app/views/sponsor-a-child/steps/25.html.erb
  app/views/sponsor-a-child/steps/26.html.erb
  app/views/sponsor-a-child/steps/27.html.erb
  app/views/sponsor-a-child/steps/28.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/30.html.erb
  app/views/sponsor-a-child/steps/31.html.erb
  app/views/sponsor-a-child/steps/32.html.erb
  app/views/sponsor-a-child/steps/33.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
  app/views/sponsor-a-child/steps/35.html.erb
  app/views/sponsor-a-child/steps/36.html.erb
  app/views/sponsor-a-child/steps/37.html.erb
  app/views/sponsor-a-child/steps/38.html.erb
  app/views/sponsor-a-child/steps/39.html.erb
  app/views/token-based-resume/select_multiple_applications.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/token_based_resume_controller_spec.rb
  spec/system/token_based_resume_controller_spec.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: bug

#256 Converts selecting an application to resume from GET to POST
  app/controllers/token_based_resume_controller.rb
  app/views/token-based-resume/select_multiple_applications.erb
  config/routes.rb
  spec/controllers/token_based_resume_controller_spec.rb
Labels: enhancement

#263 912 - Quick fix for check answers - child contact details
  app/views/sponsor-a-child/check_answers.html.erb
Labels: bug

#264 Retain child dob
  Gemfile.lock
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
  spec/system/unaccompanied_minor_minors_details_spec.rb
Labels: bug
