Repository communitiesuk/ukraine-sponsor-resettlement, pull requests merged in 2022-11, with the labels that each got.

#390 Fixed missing link in save and return functionality
  app/controllers/token_based_resume_controller.rb
Labels: bug

#404 Bedroom question bugs
  app/models/concerns/expression_of_interest_validations.rb
  config/locales/en.yml
  spec/models/individual_expression_of_interest_spec.rb
Labels: bug

#412 GitHub cypress test integration
  .github/workflows/deploy-pipeline.yml
Labels: enhancement

#428 Package.lock and Yarn.lock updates
  automated_tests/package-lock.json
  package-lock.json
  yarn.lock
Labels: dependencies

#429 Reinstating e2e tests
  .github/workflows/cypress-pipeline.yml
  .github/workflows/deploy-pipeline.yml
  automated_tests/cypress.config.js
  automated_tests/cypress/e2e/page_elements/EOI/eoi_elements.js
Labels: enhancement, dependencies

#434 Back-to link enabled when in cookies page
  app/controllers/cookies_controller.rb
  app/views/cookies/cookies.html.erb
  app/views/shared/_cookie_banner.html.erb
  app/views/shared/_cookie_success.html.erb
  automated_tests/cypress/e2e/intergration/EOI/eoi_cookies_validation.cy.js
  automated_tests/cypress/e2e/page_elements/EOI/eoi_elements.js
  automated_tests/cypress/e2e/pages/EOI/cookies_validation.js
Labels: bug

#442 Correct a typo; update gemfile
  Gemfile.lock
  automated_tests/cypress/e2e/page_elements/EOI/eoi_elements.js
  automated_tests/cypress/e2e/page_elements/Service/service_elements.js
  automated_tests/cypress/e2e/pages/EOI/address_validation.js
  automated_tests/cypress/e2e/pages/EOI/adults_&_children_validation.js
  automated_tests/cypress/e2e/pages/EOI/date_validation.js
  automated_tests/cypress/e2e/pages/EOI/e2e_hp.js
  automated_tests/cypress/e2e/pages/EOI/error_label_validation.js
  spec/rails_helper.rb
Labels: dependencies

#443 Parametrize e2e waits
  automated_tests/cypress.config.js
  automated_tests/cypress/e2e/pages/EOI/address_validation.js
  automated_tests/cypress/e2e/pages/EOI/adults_&_children_validation.js
  automated_tests/cypress/e2e/pages/EOI/date_validation.js
  automated_tests/cypress/e2e/pages/EOI/e2e_hp.js
  automated_tests/cypress/e2e/pages/EOI/error_label_validation.js
  automated_tests/cypress/e2e/pages/Service/cookies_validation.js
Labels: enhancement
