Repository communitiesuk/ukraine-sponsor-resettlement, pull requests merged in 2022-07, with the labels that each got.

#157 Add guidance page and new start flow to unaccompanied minor
  app/controllers/unaccompanied_controller.rb
  app/views/unaccompanied-minor/guidance.html.erb
  app/views/unaccompanied-minor/start.html.erb
  config/routes.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: enhancement

#158 Actionview gem updated through bundle
  package-lock.json
Labels: dependencies

#164 Fraud branch
  app/controllers/fraud_controller.rb
  app/models/abstract_confirm.rb
  app/views/fraud/fraud_page.html.erb
  config/routes.rb
  data/startup_info.json
  spec/system/fraud_controller_spec.rb
Labels: enhancement

#166 Sponsor flow
  Gemfile.lock
  app/controllers/concerns/routing_engine.rb
  app/controllers/unaccompanied_controller.rb
  app/helpers/application_helper.rb
  app/helpers/nationalities_list.csv
  app/models/concerns/contact_details_validations.rb
  app/models/concerns/uam_validations.rb
  app/models/unaccompanied_minor.rb
  app/views/unaccompanied-minor/steps/10.html.erb
  app/views/unaccompanied-minor/steps/11.html.erb
  app/views/unaccompanied-minor/steps/12.html.erb
  app/views/unaccompanied-minor/steps/13.html.erb
  app/views/unaccompanied-minor/steps/14.html.erb
  app/views/unaccompanied-minor/steps/15.html.erb
  app/views/unaccompanied-minor/steps/16.html.erb
  app/views/unaccompanied-minor/steps/17.html.erb
  app/views/unaccompanied-minor/steps/18.html.erb
  app/views/unaccompanied-minor/steps/19.html.erb
  app/views/unaccompanied-minor/steps/20.html.erb
  app/views/unaccompanied-minor/steps/21.html.erb
  app/views/unaccompanied-minor/steps/22.html.erb
  app/views/unaccompanied-minor/steps/old_views/_10.html.erb
  app/views/unaccompanied-minor/steps/old_views/_11.html.erb
  app/views/unaccompanied-minor/steps/old_views/_12.html.erb
  config/locales/en.yml
  data/startup_info.json
  spec/models/unaccompanied_minor_spec.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: enhancement

#193 Token based resume flow
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/token_based_resume_controller.rb
  app/controllers/unaccompanied_controller.rb
  app/helpers/application_helper.rb
  app/models/abstract_resume_token.rb
  app/views/token-based-resume/session_expired.html.erb
  app/views/token-based-resume/session_resume_form.html.erb
  config/routes.rb
  data/startup_info.json
  db/migrate/20220727091734_add_magic_link_to_application_tokens.rb
  db/schema.rb
  spec/models/application_token_spec.rb
  spec/system/token_based_resume_controller_spec.rb
  spec/system/unaccompanied_minor_spec.rb
Labels: enhancement

#206 Fixes the confirm and send application link in task list
  app/views/sponsor-a-child/task_list.html.erb
Labels: bug

#207 Shows Cannot start yet for Who Will Live There question if Address has not been filled in
  app/models/unaccompanied_minor.rb
  app/views/sponsor-a-child/task_list.html.erb
Labels: bug

#208 Enable Section4 only if the rest of the application is complete
  app/models/unaccompanied_minor.rb
  app/views/sponsor-a-child/task_list.html.erb
Labels: bug

#209 Remove redundant routing engine step
  app/controllers/concerns/routing_engine.rb
Labels: bug

#210 Fix other adults at address flow
  app/controllers/concerns/routing_engine.rb
  app/controllers/unaccompanied_controller.rb
  app/models/concerns/uam_validations.rb
Labels: bug

#215 Makes minor_contact_type exclusive if cannot be contacted is selected
  app/views/sponsor-a-child/steps/33.html.erb
Labels: bug

#216 Use error summary for dates of birth (sponsor, child, adults)
  app/controllers/unaccompanied_controller.rb
  app/models/concerns/uam_validations.rb
  app/views/sponsor-a-child/steps/18.html.erb
  app/views/sponsor-a-child/steps/29.html.erb
  app/views/sponsor-a-child/steps/34.html.erb
Labels: bug

#219 Update sms-based tests
  Gemfile
  Gemfile.lock
  app/controllers/token_based_resume_controller.rb
  docker-compose.yml
  spec/controllers/token_based_resume_controller_spec.rb
  spec/system/token_based_resume_controller_spec.rb
Labels: enhancement
